#!/bin/sh
# projections/visual/w3c_css.sh - CSS Layout Projection
# Generates CSS stylesheet for trace visualization
set -eu
cat << 'CSS'
/* ULP Trace CSS - Generated by π_w3c_css */
.ulp-trace { font-family: monospace; max-width: 1200px; margin: 0 auto; }
.ulp-header { background: #2d2d2d; color: #00d4ff; padding: 1rem; }
.ulp-input { background: #1a1a1a; border-left: 4px solid #00d4ff; padding: 1rem; margin: 0.5rem 0; }
.ulp-output { background: #1a1a1a; border-left: 4px solid #00ff88; padding: 1rem; margin: 0.5rem 0; white-space: pre-wrap; }
.ulp-event { background: #2d2d2d; padding: 0.5rem; margin: 0.25rem 0; border-radius: 4px; }
.ulp-timeline { list-style: none; border-left: 2px solid #404040; padding-left: 2rem; }
.ulp-exit { background: #00ff88; color: #1a1a1a; padding: 0.5rem 1rem; display: inline-block; border-radius: 4px; font-weight: bold; }
CSS
